
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 22:24:50
|      周末，不执行该任务：2
|      执行任务完毕：2    2018-12-22 22:24:51
|   开始执行任务：3    2018-12-22 22:24:51
Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.
|   开始执行任务：1    2018-12-22 22:24:51
|      执行任务完毕：1    2018-12-22 22:24:51

本批次执行的任务为：dict_values(['2'])
|   开始执行任务：2    2018-12-22 22:24:51
|      周末，不执行该任务：2
|      执行任务完毕：2    2018-12-22 22:24:51

本批次执行的任务为：dict_values(['3', '2'])
|   开始执行任务：2    2018-12-22 22:24:51
|      周末，不执行该任务：2
|      执行任务完毕：2    2018-12-22 22:24:52
|   开始执行任务：3    2018-12-22 22:24:52
Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.总共：3 个任务
本批次执行的任务为：dict_values(['1', '3', '2'])|   开始执行任务：2    2018-12-22 22:26:30|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:26:30|   开始执行任务：3    2018-12-22 22:26:30总共：3 个任务
本批次执行的任务为：dict_values(['1', '3', '2'])|   开始执行任务：2    2018-12-22 22:26:41|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:26:41|   开始执行任务：3    2018-12-22 22:26:41总共：3 个任务
本批次执行的任务为：dict_values(['1', '3', '2'])|   开始执行任务：2    2018-12-22 22:35:09|      周末，不执行该任务：2|   开始执行任务：3    2018-12-22 22:35:09|      id有失败的记录:3|   开始执行任务：1    2018-12-22 22:35:09|      id有成功的记录:1
本批次执行的任务为：dict_values(['2'])|   开始执行任务：2    2018-12-22 22:35:09|      周末，不执行该任务：2
本批次执行的任务为：dict_values(['3', '2'])|   开始执行任务：2    2018-12-22 22:35:10|      周末，不执行该任务：2|   开始执行任务：3    2018-12-22 22:35:10|      id有失败的记录:3总共：3 个任务
本批次执行的任务为：dict_values(['1', '3', '2'])|   开始执行任务：2    2018-12-22 22:35:43|      周末，不执行该任务：2|      id有成功的记录:2|   开始执行任务：3    2018-12-22 22:35:43|      id有失败的记录:3|   开始执行任务：1    2018-12-22 22:35:43|      id有成功的记录:1
本批次执行的任务为：dict_values(['2'])|   开始执行任务：2    2018-12-22 22:35:43|      周末，不执行该任务：2|      id有成功的记录:2
本批次执行的任务为：dict_values(['3', '2'])|   开始执行任务：2    2018-12-22 22:35:43|      周末，不执行该任务：2|      id有成功的记录:2|   开始执行任务：3    2018-12-22 22:35:43|      id有失败的记录:3总共：3 个任务
本批次执行的任务为：dict_values(['1', '3', '2'])|   开始执行任务：2    2018-12-22 22:35:56|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:35:56|   开始执行任务：3    2018-12-22 22:35:56总共：3 个任务
本批次执行的任务为：dict_values(['1', '3', '2'])|   开始执行任务：2    2018-12-22 22:36:29|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:36:29|   开始执行任务：3    2018-12-22 22:36:29Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.|   开始执行任务：1    2018-12-22 22:36:29|      执行任务完毕：1    2018-12-22 22:36:29
本批次执行的任务为：dict_values(['2'])|   开始执行任务：2    2018-12-22 22:36:30|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:36:30
本批次执行的任务为：dict_values(['3', '2'])|   开始执行任务：2    2018-12-22 22:36:30|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:36:30|   开始执行任务：3    2018-12-22 22:36:30Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.总共：3 个任务
执行日期为：20111019
本批次执行的任务为：dict_values(['1', '3', '2'])|   开始执行任务：2    2018-12-22 22:43:26|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:43:26|   开始执行任务：3    2018-12-22 22:43:26Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.|   开始执行任务：1    2018-12-22 22:43:26|      执行任务完毕：1    2018-12-22 22:43:26
执行日期为：20111019
本批次执行的任务为：dict_values(['2'])|   开始执行任务：2    2018-12-22 22:43:26|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:43:27
执行日期为：20111019
本批次执行的任务为：dict_values(['3', '2'])|   开始执行任务：2    2018-12-22 22:43:27|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:43:27|   开始执行任务：3    2018-12-22 22:43:27Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.
执行日期为：20100910总共：3 个任务
本批次执行的任务为：dict_values(['1', '3', '2'])|   开始执行任务：2    2018-12-22 22:44:18|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:44:18|   开始执行任务：3    2018-12-22 22:44:18Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.|   开始执行任务：1    2018-12-22 22:44:18|      执行任务完毕：1    2018-12-22 22:44:19
本批次执行的任务为：dict_values(['2'])|   开始执行任务：2    2018-12-22 22:44:19|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:44:19
本批次执行的任务为：dict_values(['3', '2'])|   开始执行任务：2    2018-12-22 22:44:19|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:44:19|   开始执行任务：3    2018-12-22 22:44:19Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.
执行日期为：20111219总共：3 个任务
本批次执行的任务为：dict_values(['1', '3', '2'])|   开始执行任务：2    2018-12-22 22:45:20|      周末，不执行该任务：2|      执行任务完毕：2    2018-12-22 22:45:20|   开始执行任务：3    2018-12-22 22:45:20

执行日期为：20180619
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 22:45:46
|      周末，不执行该任务：2
|      执行任务完毕：2    2018-12-22 22:45:47
|   开始执行任务：3    2018-12-22 22:45:47
Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.
|   开始执行任务：1    2018-12-22 22:45:47
|      执行任务完毕：1    2018-12-22 22:45:47

本批次执行的任务为：dict_values(['2'])
|   开始执行任务：2    2018-12-22 22:45:47
|      周末，不执行该任务：2
|      执行任务完毕：2    2018-12-22 22:45:47

本批次执行的任务为：dict_values(['3', '2'])
|   开始执行任务：2    2018-12-22 22:45:47
|      周末，不执行该任务：2
|      执行任务完毕：2    2018-12-22 22:45:47
|   开始执行任务：3    2018-12-22 22:45:48
Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.






执行日期为：20101114
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 22:47:41
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 22:47:41
Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.
|   开始执行任务：1    2018-12-22 22:47:41
|      执行任务完毕：1    2018-12-22 22:47:42

本批次执行的任务为：dict_values(['2'])
|   开始执行任务：2    2018-12-22 22:47:42
|      周末，不执行该任务：2

本批次执行的任务为：dict_values(['3', '2'])
|   开始执行任务：2    2018-12-22 22:47:42
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 22:47:42
Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.






执行日期为：20160111
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 22:53:52
|      周末，不执行该任务：2
|      执行任务完毕：2    2018-12-22 22:53:52
|   开始执行任务：3    2018-12-22 22:53:52
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 219, in exec_id
    subprocess.run("python %s" % script_path, shell=True, check=True)
  File "C:\Users\jr\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.

|   开始执行任务：1    2018-12-22 22:53:52
|      执行任务完毕：1    2018-12-22 22:53:52

本批次执行的任务为：dict_values(['2'])
|   开始执行任务：2    2018-12-22 22:53:52
|      周末，不执行该任务：2
|      执行任务完毕：2    2018-12-22 22:53:52

本批次执行的任务为：dict_values(['3', '2'])
|   开始执行任务：2    2018-12-22 22:53:52
|      周末，不执行该任务：2
|      执行任务完毕：2    2018-12-22 22:53:53
|   开始执行任务：3    2018-12-22 22:53:53
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 219, in exec_id
    subprocess.run("python %s" % script_path, shell=True, check=True)
  File "C:\Users\jr\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.







执行日期为：20181215
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 22:56:36
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 22:56:36
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 219, in exec_id
    subprocess.run("python %s" % script_path, shell=True, check=True)
  File "C:\Users\jr\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.

|   开始执行任务：1    2018-12-22 22:56:36
|      执行任务完毕：1    2018-12-22 22:56:36

本批次执行的任务为：dict_values(['2'])
|   开始执行任务：2    2018-12-22 22:56:36
|      周末，不执行该任务：2

本批次执行的任务为：dict_values(['3', '2'])
|   开始执行任务：2    2018-12-22 22:56:36
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 22:56:36
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 219, in exec_id
    subprocess.run("python %s" % script_path, shell=True, check=True)
  File "C:\Users\jr\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.







执行日期为：20181215
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 22:58:46
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 22:58:46
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 219, in exec_id
    subprocess.run("python %s" % script_path, shell=True, check=True)
  File "C:\Users\jr\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.

|   开始执行任务：1    2018-12-22 22:58:46
|      执行任务完毕：1    2018-12-22 22:58:46

本批次执行的任务为：dict_values(['2'])
|   开始执行任务：2    2018-12-22 22:58:46
|      周末，不执行该任务：2

本批次执行的任务为：dict_values(['3', '2'])
|   开始执行任务：2    2018-12-22 22:58:46
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 22:58:46
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 219, in exec_id
    subprocess.run("python %s" % script_path, shell=True, check=True)
  File "C:\Users\jr\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.







执行日期为：20181215
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 23:00:16
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 23:00:16
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 219, in exec_id
    subprocess.run("python %s" % script_path, shell=True, check=True)
  File "C:\Users\jr\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.







执行日期为：20181215
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 23:00:33
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 23:00:33
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 219, in exec_id
    subprocess.run("python %s" % script_path, shell=True, check=True)
  File "C:\Users\jr\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.

|   开始执行任务：1    2018-12-22 23:00:34
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 221, in exec_id
    with open(self.curr_path + r"log\task_log.csv", 'a+', encoding='utf-8') as csv:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\git_file\\python\\schedulelog\\task_log.csv'


本批次执行的任务为：dict_values(['2'])
|   开始执行任务：2    2018-12-22 23:00:34
|      周末，不执行该任务：2

本批次执行的任务为：dict_values(['3', '2'])
|   开始执行任务：2    2018-12-22 23:00:34
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 23:00:34
|      id有失败的记录:3






执行日期为：20181215
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 23:00:41
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 23:00:41
|      id有失败的记录:3
|   开始执行任务：1    2018-12-22 23:00:41
|      id有失败的记录:1

本批次执行的任务为：dict_values(['2'])
|   开始执行任务：2    2018-12-22 23:00:41
|      周末，不执行该任务：2

本批次执行的任务为：dict_values(['3', '2'])
|   开始执行任务：2    2018-12-22 23:00:41
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 23:00:41
|      id有失败的记录:3






执行日期为：20181215
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 23:01:54
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 23:01:54
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 219, in exec_id
    subprocess.run("python %s" % script_path, shell=True, check=True)
  File "C:\Users\jr\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.

|   开始执行任务：1    2018-12-22 23:01:55
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 221, in exec_id
    with open(self.curr_path + r"log\task_log.csv", 'a+', encoding='utf-8') as csv:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\git_file\\python\\schedulelog\\task_log.csv'


本批次执行的任务为：dict_values(['2'])
|   开始执行任务：2    2018-12-22 23:01:55
|      周末，不执行该任务：2

本批次执行的任务为：dict_values(['3', '2'])
|   开始执行任务：2    2018-12-22 23:01:55
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 23:01:55
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 219, in exec_id
    subprocess.run("python %s" % script_path, shell=True, check=True)
  File "C:\Users\jr\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.







执行日期为：20180218
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 23:14:35
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 23:14:35






执行日期为：20111126
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 23:18:10
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 23:18:10






执行日期为：20121229
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 23:18:27
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 23:18:27
['Traceback (most recent call last):\n', '  File "E:/git_file/python/schedule/myschedule.py", line 226, in exec_id\n    subprocess.run("python %s" % script_path, shell=True, check=True)\n', '  File "C:\\Users\\jr\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\n', "subprocess.CalledProcessError: Command 'python E:\\git_file\\python\\schedule\\jobs\\hellow3.py' returned non-zero exit status 1.\n"]
|   开始执行任务：1    2018-12-22 23:18:27
['Traceback (most recent call last):\n', '  File "E:/git_file/python/schedule/myschedule.py", line 228, in exec_id\n    with open(self.curr_path + r"log\\task_log.csv", \'a+\', encoding=\'utf-8\') as csv:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'E:\\\\git_file\\\\python\\\\schedulelog\\\\task_log.csv'\n"]

本批次执行的任务为：dict_values(['2'])
|   开始执行任务：2    2018-12-22 23:18:28
|      周末，不执行该任务：2

本批次执行的任务为：dict_values(['3', '2'])
|   开始执行任务：2    2018-12-22 23:18:28
|      周末，不执行该任务：2
|   开始执行任务：3    2018-12-22 23:18:28
|      id有失败的记录:3






执行日期为：20191111
总共：3 个任务

本批次执行的任务为：dict_values(['1', '3', '2'])
|   开始执行任务：2    2018-12-22 23:20:26
|      周末，不执行该任务：2
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 228, in exec_id
    with open(self.curr_path + r"log\task_log.csv", 'a+', encoding='utf-8') as csv:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\git_file\\python\\schedulelog\\task_log.csv'

|   开始执行任务：3    2018-12-22 23:20:26
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 226, in exec_id
    subprocess.run("python %s" % script_path, shell=True, check=True)
  File "C:\Users\jr\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python E:\git_file\python\schedule\jobs\hellow3.py' returned non-zero exit status 1.

|   开始执行任务：1    2018-12-22 23:20:27
Traceback (most recent call last):
  File "E:/git_file/python/schedule/myschedule.py", line 228, in exec_id
    with open(self.curr_path + r"log\task_log.csv", 'a+', encoding='utf-8') as csv:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\git_file\\python\\schedulelog\\task_log.csv'


本批次执行的任务为：dict_values(['2'])
|   开始执行任务：2    2018-12-22 23:20:27
|      周末，不执行该任务：2
|      id有失败的记录:2

本批次执行的任务为：dict_values(['3', '2'])
|   开始执行任务：2    2018-12-22 23:20:27
|      周末，不执行该任务：2
|      id有失败的记录:2
|   开始执行任务：3    2018-12-22 23:20:27
|      id有失败的记录:3